/**
 * Compile-time app registry generator.
 *
 * Scans each "apps/<id>/app.yaml", validates every manifest against the
 * Manifest v1 contract and emits static import tables for backend and frontend:
 *
 *   backend/src/generated/apps.ts   -> backendAppModules + frontendAppIds
 *   frontend/src/generated/apps.ts  -> frontendAppModules + frontendAppIds
 *
 * The build fails on any invalid manifest so a broken app cannot ship.
 *
 * Usage: npm run generate:apps [-- --check]
 *   --check: regenerate in memory and fail if the committed files are stale.
 *
 * scan(root) is exported for reuse (scripts/verify-apps.ts); the generation
 * CLI below only runs when this file is the process entry point.
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { parse } from "yaml";
import { semanticErrors, validateManifest } from "../backend/src/core/app-registry/manifest.js";

export interface AppEntry {
  id: string;
  hasBackend: boolean;
  hasFrontend: boolean;
}

export function scan(root: string): AppEntry[] {
  const appsDir = join(root, "apps");
  if (!existsSync(appsDir)) {
    console.error(`generate:apps: apps directory not found at ${appsDir}`);
    process.exit(1);
  }
  const entries = readdirSync(appsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && !entry.name.startsWith("_") && !entry.name.startsWith("."))
    .sort((a, b) => a.name.localeCompare(b.name));

  const seen = new Set<string>();
  const apps: AppEntry[] = [];
  let invalid = false;

  for (const entry of entries) {
    const manifestPath = join(appsDir, entry.name, "app.yaml");
    if (!existsSync(manifestPath)) continue;

    let parsed: unknown;
    try {
      parsed = parse(readFileSync(manifestPath, "utf8"));
    } catch (error) {
      console.error(`generate:apps: ${entry.name}/app.yaml: YAML parse failed: ${String(error)}`);
      invalid = true;
      continue;
    }

    const result = validateManifest(parsed);
    if (!result.ok) {
      console.error(`generate:apps: ${entry.name}/app.yaml invalid:\n  - ${result.errors.join("\n  - ")}`);
      invalid = true;
      continue;
    }
    const semantic = semanticErrors(result.manifest);
    if (semantic.length > 0) {
      console.error(`generate:apps: ${entry.name}/app.yaml invalid:\n  - ${semantic.join("\n  - ")}`);
      invalid = true;
      continue;
    }
    if (seen.has(result.manifest.id)) {
      console.error(`generate:apps: duplicate app id "${result.manifest.id}"`);
      invalid = true;
      continue;
    }
    seen.add(result.manifest.id);

    apps.push({
      id: result.manifest.id,
      hasBackend: existsSync(join(root, "backend", "src", "apps", result.manifest.id, "index.ts")),
      hasFrontend:
        existsSync(join(root, "frontend", "src", "apps", result.manifest.id, "index.tsx")) ||
        existsSync(join(root, "frontend", "src", "apps", result.manifest.id, "index.ts")),
    });
  }

  if (invalid) process.exit(1);
  return apps;
}

function renderBackend(apps: AppEntry[]): string {
  const imports = apps
    .filter((app) => app.hasBackend)
    .map((app) => `import ${app.id} from "../apps/${app.id}/index.js";`)
    .join("\n");
  const entries = apps
    .filter((app) => app.hasBackend)
    .map((app) => `  ${app.id},`)
    .join("\n");
  const ids = apps
    .filter((app) => app.hasFrontend)
    .map((app) => `  "${app.id}",`)
    .join("\n");
  return `// AUTO-GENERATED by scripts/generate-apps-registry.ts — do not edit.
// Regenerate with: npm run generate:apps
import type { BackendAppModule } from "../core/app-registry/types.js";
${imports}

export const backendAppModules: Record<string, BackendAppModule> = {
${entries}
};

/** Apps that ship a frontend module; mirrors frontend/src/generated/apps.ts. */
export const frontendAppIds: string[] = [
${ids}
];
`;
}

function renderFrontend(apps: AppEntry[]): string {
  const imports = apps
    .filter((app) => app.hasFrontend)
    .map((app) => `import ${app.id} from "../apps/${app.id}/index";`)
    .join("\n");
  const entries = apps
    .filter((app) => app.hasFrontend)
    .map((app) => `  ${app.id},`)
    .join("\n");
  const ids = apps
    .filter((app) => app.hasFrontend)
    .map((app) => `  "${app.id}",`)
    .join("\n");
  return `// AUTO-GENERATED by scripts/generate-apps-registry.ts — do not edit.
// Regenerate with: npm run generate:apps
import type { FrontendAppModule } from "../shared/appTypes";
${imports}

export const frontendAppModules: Record<string, FrontendAppModule> = {
${entries}
};

export const frontendAppIds: string[] = [
${ids}
];
`;
}

// ---- CLI (only active when this file is the process entry point) ----

function run(): void {
  const root = process.cwd();
  const checkOnly = process.argv.includes("--check");
  const apps = scan(root);
  const backendPath = join(root, "backend", "src", "generated", "apps.ts");
  const frontendPath = join(root, "frontend", "src", "generated", "apps.ts");
  const backendOut = renderBackend(apps);
  const frontendOut = renderFrontend(apps);

  if (checkOnly) {
    const stale: string[] = [];
    if (readFileSync(backendPath, "utf8") !== backendOut) stale.push(backendPath);
    if (readFileSync(frontendPath, "utf8") !== frontendOut) stale.push(frontendPath);
    if (stale.length > 0) {
      console.error(`generate:apps: generated files are stale (run npm run generate:apps):\n  ${stale.join("\n  ")}`);
      process.exit(1);
    }
    console.log(`generate:apps: ${apps.length} app(s) up to date`);
  } else {
    mkdirSync(join(root, "backend", "src", "generated"), { recursive: true });
    mkdirSync(join(root, "frontend", "src", "generated"), { recursive: true });
    writeFileSync(backendPath, backendOut);
    writeFileSync(frontendPath, frontendOut);
    console.log(
      `generate:apps: wrote ${backendPath} and ${frontendPath} (${apps.length} app(s), ` +
        `${apps.filter((a) => a.hasBackend).length} backend, ${apps.filter((a) => a.hasFrontend).length} frontend)`,
    );
  }
}

const isDirectRun = (() => {
  if (!process.argv[1]) return false;
  try {
    return realpathSync(process.argv[1]) === realpathSync(fileURLToPath(import.meta.url));
  } catch {
    return false;
  }
})();

if (isDirectRun) run();
